[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
optimizer = true
optimizer_runs = 200
remappings = [
    "solidity-bytes-utils/=node_modules/solidity-bytes-utils/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@ensdomains/ens-contracts/=lib/ens-contracts/",
]